// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_body: dynamic(() => import("./BlogBody")),
  article_header: dynamic(() => import("./BlogHero")),
};
